obj-y					+= fuse-tegra.o
obj-y					+= fuse-tegra30.o
obj-$(CONFIG_ARCH_TEGRA_2x_SOC)		+= fuse-tegra20.o
obj-$(CONFIG_ARCH_TEGRA_2x_SOC)		+= tegra20_speedo.o
obj-$(CONFIG_ARCH_TEGRA_3x_SOC)		+= tegra30_speedo.o
obj-$(CONFIG_ARCH_TEGRA_114_SOC)	+= tegra114_speedo.o
obj-$(CONFIG_ARCH_TEGRA_124_SOC)	+= tegra124_speedo.o
obj-$(CONFIG_TEGRA_KFUSE)		+= tegra-kfuse.o
