
# platform configuration for board devices
obj-y					+= device_libs/

# INTEL-MID specific files
obj-$(CONFIG_X86_INTEL_MID)		+= intel-common.o

# Standalone Baytrail Maxim 98090 codec initialization
obj-$(CONFIG_SND_BYT_MAX98090)		+= intel-byt-sound.o
