/*
 * <Driver for I2S protocol on SSP (Moorestown and Medfield hardware)>
 * Copyright (c) 2010, Intel Corporation.
 * Louis LE GALL <louis.le.gall intel.com>
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms and conditions of the GNU General Public License,
 * version 2, as published by the Free Software Foundation.
 *
 * This program is distributed in the hope it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin St - Fifth Floor, Boston, MA 02110-1301 USA.
 */
#ifndef MID_I2S_COMMON_H_
#define MID_I2S_COMMON_H_

#include <linux/types.h>

/*
 *	SSCR0 settings
 */

enum mrst_ssp_mode {
	SSP_IN_NORMAL_MODE = 0x0,
	SSP_IN_NETWORK_MODE,
	SSP_INVALID_MODE = 0xF
};

enum mrst_ssp_rx_fifo_over_run_int_mask {
	SSP_RX_FIFO_OVER_INT_ENABLE = 0x0,
	SSP_RX_FIFO_OVER_INT_DISABLE
};

enum mrst_ssp_tx_fifo_under_run_int_mask {
	SSP_TX_FIFO_UNDER_INT_ENABLE = 0x0,
	SSP_TX_FIFO_UNDER_INT_DISABLE
};

enum mrst_ssp_frame_format {
	MOTOROLA_SPI_FORMAT = 0x0,
	TI_SSP_FORMAT,
	MICROWIRE_FORMAT,
	PSP_FORMAT

};

enum mrst_ssp_master_mode_clock_selection {
	SSP_ONCHIP_CLOCK = 0x0,
	SSP_NETWORK_CLOCK,
	SSP_EXTERNAL_CLOCK,
	SSP_ONCHIP_AUDIO_CLOCK,
	SSP_MASTER_CLOCK_UNDEFINED = 0xFF
};

/*
 * Following enum and define are for frequency calculation in master mode...
 */

enum mrst_ssp_frm_freq {
	SSP_FRM_FREQ_UNDEFINED = 0,
	SSP_FRM_FREQ_48_000,
	SSP_FRM_FREQ_44_100,
	SSP_FRM_FREQ_22_050,
	SSP_FRM_FREQ_16_000,
	SSP_FRM_FREQ_11_025,
	SSP_FRM_FREQ_8_000,
	SSP_FRM_FREQ_SIZE
};

/*
 *	SSCR1 settings
 */
enum mrst_ssp_txd_tristate_last_phase {
	TXD_TRISTATE_LAST_PHASE_OFF =  0x0,
	TXD_TRISTATE_LAST_PHASE_ON
};

enum mrst_ssp_txd_tristate_enable {
	TXD_TRISTATE_OFF =  0x0,
	TXD_TRISTATE_ON
};

enum mrst_ssp_slave_sspclk_free_running {
	SLAVE_SSPCLK_ON_ALWAYS =  0x0,
	SLAVE_SSPCLK_ON_DURING_TRANSFER_ONLY
};

enum mrst_ssp_sspsclk_direction {
	SSPSCLK_MASTER_MODE = 0x0,
	SSPSCLK_SLAVE_MODE
};

enum mrst_ssp_sspsfrm_direction {
	SSPSFRM_MASTER_MODE = 0x0,
	SSPSFRM_SLAVE_MODE
};

enum mrst_ssp_rx_without_tx {
	RX_AND_TX_MODE = 0x0,
	RX_WITHOUT_TX_MODE
};

enum mrst_trailing_byte_mode {
	SSP_TRAILING_BYTE_HDL_BY_IA = 0x0,
	SSP_TRAILING_BYTE_HDL_BY_DMA
};

enum mrst_ssp_tx_dma_status {
	SSP_TX_DMA_MASK = 0x0,
	SSP_TX_DMA_ENABLE
};

enum mrst_ssp_rx_dma_status {
	SSP_RX_DMA_MASK = 0x0,
	SSP_RX_DMA_ENABLE
};

enum mrst_ssp_rx_timeout_int_status {
	SSP_RX_TIMEOUT_INT_DISABLE = 0x0,
	SSP_RX_TIMEOUT_INT_ENABLE
};

enum mrst_ssp_trailing_byte_int_status {
	SSP_TRAILING_BYTE_INT_DISABLE = 0x0,
	SSP_TRAILING_BYTE_INT_ENABLE
};

enum mrst_ssp_loopback_mode_status {
	SSP_LOOPBACK_OFF = 0x0,
	SSP_LOOPBACK_ON
};

/*
 *	SSPSP settings: for PSP Format ONLY!!!!!!!!
 */

enum mrst_ssp_frame_sync_relative_timing_bit {
	NEXT_FRMS_ASS_AFTER_END_OF_T4 =  0x0,
	NEXT_FRMS_ASS_WITH_LSB_PREVIOUS_FRM
};

enum mrst_ssp_frame_sync_polarity_bit {
	SSP_FRMS_ACTIVE_LOW =  0x0,
	SSP_FRMS_ACTIVE_HIGH
};

enum mrst_ssp_end_of_transfer_data_state {
	SSP_END_DATA_TRANSFER_STATE_LOW = 0x0,
	SSP_END_DATA_TRANSFER_STATE_PEVIOUS_BIT
};

enum mrst_ssp_clk_mode {
	SSP_CLK_MODE_0 = 0x0,
	SSP_CLK_MODE_1,
	SSP_CLK_MODE_2,
	SSP_CLK_MODE_3
};

enum mrst_ssp_mn_divider_bypass {
	BYPASS  =0x0,
	NO_BYPASS
};

enum mrst_ssp_mn_divider_enable {
	DIV_DISABLE = 0x0,
	DIV_ENABLE
};

enum mrst_ssp_mn_divider_update {
	MN_N0_UPDATE = 0x0,
	MN_UPDATE
};
/*
 *	Structure used to configure the SSP Port
 *	Please note that only the PSP format and the DMA transfer are supported
 *
 *      mode : Normal or Network (Network typically used in systems where
 *       several devices are connected to same TX, RX, FRMS, CLK...
 *      rx_fifo_interrupt : mask fifo over run interrupts.
 *      tx_fifo_interrupt : mask fifo under run interrupts.
 *      frame_format : 4 format available. PSP is Programmable Serial Protocol
 *	master_mode_clk_selection : select which clock will be used to generate
 *        the clock in master mode.
 *      frame_rate_divider_control : number of time slots used in network mode.
 *	 however, this is second priority vs doing required framesync clock in
 *	 master mode (this number may be increased to reach correct framesync
 *	 rate). The active tx & rx slot map will be limit the real active slots.
 *	master_mode_standard_freq : in master mode, select which standard frame
 *	 frequency you want to be generated by SSP.
 *	data_size : size in bits of each sample. In master mode only 8, 16 or 32
 *	 data sizes are supported.
 *	tx_tristate_phase : tri state phase (see langwell spec...)
 *	tx_tristate_enable : enable tri state of tx when not transmitting data.
 *
 */
struct intel_mid_i2s_settings {
	enum mrst_ssp_mode                        mode; //SSCR0 - MOD - 1 (Network Mode)
	enum mrst_ssp_rx_fifo_over_run_int_mask   rx_fifo_interrupt; 
	enum mrst_ssp_tx_fifo_under_run_int_mask  tx_fifo_interrupt;
	enum mrst_ssp_frame_format                frame_format; //SSCR0 - FRF - 11 (Programmable Serial Protocol- PSP)
	/* below for Master Mode Only */
	enum mrst_ssp_master_mode_clock_selection master_mode_clk_selection;
	__u8                                      frame_rate_divider_control;
	/* below for Master Mode Only */
	enum mrst_ssp_frm_freq                    master_mode_standard_freq;

	__u16                                     data_size;

	enum mrst_ssp_txd_tristate_last_phase     tx_tristate_phase; //SSCR1 - TTELP - 1 (TXD line will be tristated 1/2 clock edge after TXD is to be flopped)
	enum mrst_ssp_txd_tristate_enable         tx_tristate_enable; //SSCR1 - TTE - 1 (TXD line will be tristated when no transmitting data)
	enum mrst_ssp_slave_sspclk_free_running   slave_clk_free_running_status; //SSCR1 - SCFR - 0 (clock input to SSPSCLK is continuously running)
	enum mrst_ssp_sspsclk_direction           sspslclk_direction; //SSCR1 - SCLKDIR - 0 (Master mode, SSP drives SSPSCLK)
	enum mrst_ssp_sspsfrm_direction           sspsfrm_direction; //SSCR1 - SFRMDIR - 0 (Master mode, SSP drives SSPSFRM)
	enum mrst_ssp_rx_without_tx               ssp_duplex_mode; //SSCR1 - RWOT - 0 (Transmit/Receive mode)
	enum mrst_trailing_byte_mode              ssp_trailing_byte_mode; //SSCR1 - TRAIL - 0 (Processor based, trailing bytes are handled by processor)
	enum mrst_ssp_tx_dma_status               ssp_tx_dma; //SSCR1 - TSRE - 1 (DMA Service Request is enabled)
	enum mrst_ssp_rx_dma_status               ssp_rx_dma; //SSCR1 - RSRE - 1 (DMA Service Request is enabled)
	enum mrst_ssp_rx_timeout_int_status
					ssp_rx_timeout_interrupt_status; //SSCR1 - TINTE - 0 (Receiver Time-out interrupts are disabled)
	enum mrst_ssp_trailing_byte_int_status
					ssp_trailing_byte_interrupt_status; //SSCR1 - PINTE - 0 (Peripheral Trailing Byte Interrupts are disabled)
	enum mrst_ssp_loopback_mode_status        ssp_loopback_mode_status; //not sure
	__u8                                      ssp_rx_fifo_threshold; //SSCR1 - RFT - 0111
	__u8                                      ssp_tx_fifo_threshold; //SSCR1 - TFT - 0111


	enum mrst_ssp_frame_sync_relative_timing_bit  ssp_frmsync_timing_bit; //SSPSP - FSRT - 0 (Next frame is asserted after the end of the T4 timing)
	enum mrst_ssp_frame_sync_polarity_bit     ssp_frmsync_pol_bit; //SSPSP - SFRMP - 1 (SSPSFRM is active high)
	enum mrst_ssp_end_of_transfer_data_state  ssp_end_transfer_state; //SSPSP - ETDS - 0 (Low)
	enum mrst_ssp_clk_mode                    ssp_serial_clk_mode; //SSPSP - SCMODE - 00 (Data driven (falling), Data sampled (rising), Idle state (low))
	__u8                                      ssp_psp_T1;
	__u8                                      ssp_psp_T2;
	__u8                                      ssp_psp_T4;   /* DMYSTOP */ //SSPSP - 00
	__u8                                      ssp_psp_T5;   /* SFRMDLY */ //SSPSP - 0000000
	__u8                                      ssp_psp_T6;   /* SFRMWDTH */ //SSPSP - 000000

	__u8                                      ssp_active_tx_slots_map;
	__u8                                      ssp_active_rx_slots_map;
	enum mrst_ssp_mn_divider_bypass			  ssp_divider_bypass;
	enum mrst_ssp_mn_divider_enable			  ssp_divider_enable;
	enum mrst_ssp_mn_divider_update			  ssp_divider_update;
	__u32									  m_value;
	__u32									  n_value;
};

#endif /* MID_I2S_COMMON_H_*/
